development:
  clients:
    default:
      uri: mongodb://admineisenar:Cesarpaco2020@mngdb02.dinaserver.com/eisenar

test:
  clients:
    default:
      uri: mongodb://admineisenar:Cesarpaco2020@mngdb02.dinaserver.com/eisenar

production:
  clients:
    default:
      uri: mongodb://admineisenar:Cesarpaco2020@mngdb02.dinaserver.com/eisenar
